### ISSUE TITLE
Issue with Follow Button

### ISSUE THREAD

**Issue by laticauda-64** [adr1enbe4udou1n/react-ts-realworld-example-app#1]
In ArticleShow component, the "Follow/Unfollow" button works fine but not in AuthorLayout where the button is stuck in his original state.

**Comment by adr1enbe4udou1n** [comment]
Sorry I'm mistaken on the default master branch, checkout the new default main branch for last developments that fixed this bug before your feedback.

So I close your PR because I'm using a completly different approach with `useQuery` from https://tanstack.com/ which get rid of manual update code for this kind of component.

**Comment by laticauda-64** [comment]
Ok, snif, moi qui était tout content avec ma PR...
Super travail en tout cas tes repos m'aide beaucoup pour me remettre dans React & Nestjs !!! La qualité du code/organisation me bluffe... J'ai du boulot pour arriver à ton niveau. Merci pour le partage.
